---
apiVersion: v2
name: my-cert-manager
type: application
description: Cert Manager Helm Chart for Kubernetes
appVersion: "0.1.0"
version: 0.1.0
keywords:
  - cert-manager
  - letsencrypt
  - tls
  - ssl
dependencies:
  - name: cert-manager
    version: v1.19.2
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled