acme:
  email: "" # Email address for Let's Encrypt registration

cloudflare:
  apiToken: "" # Plain API token; templating handles base64 encoding

cert-manager:
  enabled: true # Enable cert-manager subchart
  crds:
    enabled: false # CRD are installed separately via Makefile
    keep: true # Set to true to keep CRDs after uninstalling the charts