apiVersion: v1
data:
  api-token: {{ .Values.cloudflare.apiToken | required "cloudflare.apiToken is required" | b64enc | quote }}
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager